
# FLASK
DEBUG = True
SECRET_KEY = 'secret_level'

# FLASKMAP
PROVIDER = 'file'
GOOGLE_MAPS_API_KEY = 'AIzaSyAE2HNuleCVfTxrq9ip1uq8IA69XZenAcg'

# FILE STORE PROVIDER
FILESTORE_PATH = '/vagrant/bin/data/'
FILESTORE_REMOVE_PERMANENT = False

# MONGODB STORE PROVIDER
MONGODB_HOST = 'localhost'
MONGODB_PORT = 27017
